version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Asia/Bangkok
    open-pull-requests-limit: 5
    groups:
      production-patches:
        dependency-type: production
        update-types:
          - patch
          - minor
      development-patches:
        dependency-type: development
        update-types:
          - patch
          - minor
    labels:
      - dependencies
      - security

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - security
