import { Search } from "lucide-react";
import { StoryCard } from "@/components/content-cards";
import { EmptyPublicResults, PublicPagination } from "@/components/public-pagination";
import { createMetadata } from "@/lib/seo";
import { PublicContentService } from "@/server/services/public-content.service";

export const metadata = createMetadata({ title: "ข่าวสารและบทความ", description: "ข่าวบริษัท กิจกรรม โปรโมชัน และความรู้เรื่องระบบปรับอากาศ", path: "/news" });
type Params = { q?: string; category?: string; page?: string };
export default async function NewsPage({ searchParams }: { searchParams: Promise<Params> }) { const raw = await searchParams; const page = Math.max(1, Number.parseInt(raw.page ?? "1", 10) || 1); const content = new PublicContentService(); const [result, categories] = await Promise.all([content.listNews({ page, pageSize: 9, query: raw.q, categorySlug: raw.category }), content.getNewsCategories()]); const items = result.items.map(item => ({ slug: item.slug, title: item.title, category: item.category.name, date: item.publishedAt ? new Intl.DateTimeFormat("th-TH", { dateStyle: "medium" }).format(item.publishedAt) : undefined, summary: item.summary, tone: "mint", media: item.coverMedia })); return <><section className="page-hero"><div className="container"><p className="eyebrow">NEWS & KNOWLEDGE</p><h1 className="display">ข่าวสารและบทความ</h1><p className="lead">ติดตามข่าวบริษัท กิจกรรม โปรโมชัน และสาระเกี่ยวกับการดูแลระบบปรับอากาศ</p></div></section><section className="section"><div className="container"><form className="filters" action="/news"><label className="search-field"><span className="sr-only">ค้นหาข่าว</span><Search size={18} /><input className="field" name="q" defaultValue={raw.q} maxLength={120} placeholder="ค้นหาข่าวหรือบทความ" /></label><select className="select filter-select" name="category" defaultValue={raw.category ?? ""} aria-label="กรองตามหมวดหมู่"><option value="">ทุกหมวดหมู่</option>{categories.map(value => <option key={value.id} value={value.slug}>{value.name}</option>)}</select><button className="btn btn-dark" type="submit">ค้นหา</button></form><p className="muted">พบ {result.total} รายการ</p>{items.length ? <div className="grid-3">{items.map(item => <StoryCard key={item.slug} item={item} type="news" />)}</div> : <EmptyPublicResults resetHref="/news" />}<PublicPagination page={result.page} pageCount={result.pageCount} pathname="/news" params={{ q: raw.q, category: raw.category }} /></div></section></>; }
