import { Search } from "lucide-react";
import { StoryCard } from "@/components/content-cards";
import { EmptyPublicResults, PublicPagination } from "@/components/public-pagination";
import { createMetadata } from "@/lib/seo";
import { PublicContentService } from "@/server/services/public-content.service";

export const metadata = createMetadata({ title: "ผลงาน", description: "ตัวอย่างผลงานติดตั้ง บำรุงรักษาระบบปรับอากาศ และงานระบบ M&E", path: "/projects" });
type Params = { q?: string; projectType?: string; page?: string };
export default async function ProjectsPage({ searchParams }: { searchParams: Promise<Params> }) { const raw = await searchParams; const page = Math.max(1, Number.parseInt(raw.page ?? "1", 10) || 1); const content = new PublicContentService(); const [result, types] = await Promise.all([content.listProjects({ page, pageSize: 9, query: raw.q, projectType: raw.projectType }), content.getProjectTypes()]); const items = result.items.map(item => ({ slug: item.slug, title: item.title, category: item.projectType, area: item.area, date: item.completedAt ? new Intl.DateTimeFormat("th-TH", { year: "numeric", month: "short" }).format(item.completedAt) : undefined, summary: item.summary, tone: "office", media: item.coverMedia })); return <><section className="page-hero"><div className="container"><p className="eyebrow">OUR PROJECTS</p><h1 className="display">ผลงานของเรา</h1><p className="lead">ตัวอย่างงานติดตั้ง บำรุงรักษา และงานระบบวิศวกรรมที่ได้รับการดูแลอย่างเป็นขั้นตอน</p></div></section><section className="section"><div className="container"><form className="filters" action="/projects"><label className="search-field"><span className="sr-only">ค้นหาผลงาน</span><Search size={18} /><input className="field" name="q" defaultValue={raw.q} maxLength={120} placeholder="ค้นหาชื่อผลงานหรือพื้นที่" /></label><select className="select filter-select" name="projectType" defaultValue={raw.projectType ?? ""} aria-label="กรองตามประเภท"><option value="">ทุกประเภท</option>{types.map(value => <option key={value.projectType}>{value.projectType}</option>)}</select><button className="btn btn-dark" type="submit">ค้นหา</button></form><p className="muted">พบ {result.total} รายการ</p>{items.length ? <div className="grid-3">{items.map(item => <StoryCard key={item.slug} item={item} type="projects" />)}</div> : <EmptyPublicResults resetHref="/projects" />}<PublicPagination page={result.page} pageCount={result.pageCount} pathname="/projects" params={{ q: raw.q, projectType: raw.projectType }} /></div></section></>; }
