import { BadgeCheck, HeartHandshake, ShieldCheck, Users } from "lucide-react";
import { createMetadata } from "@/lib/seo";
import { PublicContentService } from "@/server/services/public-content.service";

export const metadata = createMetadata({ title: "เกี่ยวกับเรา", description: "รู้จักบริษัท อยู่เย็นเป็นสุข วิศวกรรม จำกัด วิสัยทัศน์ พันธกิจ และแนวทางการทำงาน", path: "/about" });

export default async function AboutPage() { const company = await new PublicContentService().getCompany();
  return <><section className="page-hero"><div className="container"><p className="eyebrow">ABOUT US</p><h1 className="display">งานวิศวกรรมที่ดี<br />เริ่มจากความใส่ใจ</h1><p className="lead">{company?.shortDescription ?? "เราให้บริการระบบปรับอากาศและงานระบบอาคาร โดยยึดความเหมาะสมของพื้นที่ ความปลอดภัย และการดูแลในระยะยาวเป็นสำคัญ"}</p></div></section><section className="section"><div className="container detail-grid"><div className="media office media-office" style={{ minHeight: 470, borderRadius: 24 }} role="img" aria-label="ภาพสำนักงานบริษัท" /><div><p className="eyebrow">OUR STORY</p><h2 className="heading">อยู่เย็น เป็นสุข<br />ในทุกพื้นที่ใช้งาน</h2><p className="lead" style={{ whiteSpace: "pre-wrap" }}>{company?.history ?? "บริษัท อยู่เย็นเป็นสุข วิศวกรรม จำกัด ก่อตั้งขึ้นจากความตั้งใจที่จะทำให้งานระบบปรับอากาศเป็นเรื่องเข้าใจง่าย"}</p></div></div></section><section className="section band"><div className="container"><div className="grid-3"><article className="process-item"><BadgeCheck color="var(--lime-400)" /><h2>วิสัยทัศน์</h2><p>{company?.vision ?? "เป็นทีมวิศวกรรมที่ลูกค้าไว้วางใจ"}</p></article><article className="process-item"><HeartHandshake color="var(--lime-400)" /><h2>พันธกิจ</h2><p>{company?.mission ?? "ส่งมอบงานที่เหมาะกับผู้ใช้งาน โปร่งใส และรับผิดชอบ"}</p></article><article className="process-item"><ShieldCheck color="var(--lime-400)" /><h2>คุณค่าของเรา</h2><p>จริงใจ เป็นระบบ ปลอดภัย และพร้อมพัฒนาคุณภาพงานอย่างต่อเนื่อง</p></article></div></div></section><section className="section"><div className="container" style={{ textAlign: "center" }}><Users size={34} color="var(--green-700)" /><h2 className="heading" style={{ marginTop: 18 }}>ทีมที่พร้อมดูแลคุณ</h2></div></section></>;
}
