import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { currentSession } from "@/server/auth/session";
import { updateAdminSafely } from "@/server/auth/admin-users";
import { assertSameOrigin } from "@/server/security/request";
import { requestContext } from "@/server/security/request";
import { audit } from "@/server/auth/audit";
const schema = z.object({ displayName: z.string().trim().min(1).max(120).optional(), role: z.enum(["EDITOR", "SUPER_ADMIN"]).optional(), isActive: z.boolean().optional() }).strict();
export async function PATCH(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { if (!assertSameOrigin(request)) return NextResponse.json({ error: "Invalid request" }, { status: 403 }); const session = await currentSession(); const parsed = schema.safeParse(await request.json().catch(() => null)); if (!session?.twoFactorAt || session.admin.role !== "SUPER_ADMIN") return NextResponse.json({ error: "Forbidden" }, { status: 403 }); if (!parsed.success) return NextResponse.json({ error: "Invalid request" }, { status: 400 }); const id = (await params).id; try { const user = await updateAdminSafely(id, parsed.data); await audit({ actorId: session.adminId, action: "ADMIN_UPDATED", targetType: "Admin", targetId: id, result: "SUCCESS", metadata: { changedRole: parsed.data.role !== undefined, changedStatus: parsed.data.isActive !== undefined }, ...requestContext(request) }); return NextResponse.json({ user }); } catch (error) { await audit({ actorId: session.adminId, action: "ADMIN_UPDATED", targetType: "Admin", targetId: id, result: "FAILURE", ...requestContext(request) }); return NextResponse.json({ error: error instanceof Error && error.message === "LAST_SUPER_ADMIN" ? "ไม่สามารถเปลี่ยน Super Admin คนสุดท้ายได้" : "ไม่สามารถบันทึกได้" }, { status: 409 }); } }
